build: add missing #include to cure compile error
[g++-14 complains:

mission_download.cpp:402:19: error: variable ‘std::fstream in’ has initializer but incomplete type
  402 |   std::fstream in(qualfile, std::ios::binary | std::ios::trunc | std::ios::out);

–jengelh]